(ns kami.sculpt.app (:require [kami.sculpt :as sculpt] [kami.webgpu.mesh :as gpu]))
(def base (sculpt/sphere-mesh 1.5 32 20))
(defonce state (atom {:mesh base :mode :inflate :radius 0.6 :strength 0.12 :symmetry :x :history [] :future [] :strokes 0}))
(defonce viewport (atom nil))
(defn- upload! [] (when-let [v @viewport] (swap! viewport assoc :buffers (gpu/upload-mesh! (:mesh-context v) (:mesh @state))) (set! (.-textContent (.getElementById js/document "stats")) (str (count (:positions (:mesh @state))) " vertices · " (/ (count (:indices (:mesh @state))) 3) " triangles · " (:strokes @state) " strokes"))))
(defn- draw! [] (when-let [{:keys [buffers] :as v} @viewport] (when buffers (gpu/render-frame! v buffers [0 1 5] [0 0 0] [0.85 0.42 0.58]))) (js/requestAnimationFrame draw!))
(defn- brush-at! [canvas e]
 (let [r (.getBoundingClientRect canvas) nx (- (* 2 (/ (- (.-clientX e) (.-left r)) (.-width r))) 1) ny (- 1 (* 2 (/ (- (.-clientY e) (.-top r)) (.-height r)))) z (js/Math.sqrt (max 0 (- 1 (* nx nx) (* ny ny)))) center [(* 1.5 nx) (* 1.5 ny) (* 1.5 z)] b (sculpt/brush center (:radius @state) (:strength @state) (:mode @state))] (swap! state update :mesh sculpt/apply-stroke b (:symmetry @state)) (upload!)))
(defn ^:export init! [] (let [canvas (.getElementById js/document "gpu-canvas") dragging (atom false)]
 (-> (gpu/init-canvas! canvas) (.then (fn [v] (reset! viewport v) (upload!) (set! (.-textContent (.getElementById js/document "gpu-status")) "") (draw!))))
 (doseq [b (array-seq (.querySelectorAll js/document "[data-mode]"))] (.addEventListener b "click" #(do (doseq [x (array-seq (.querySelectorAll js/document "[data-mode]"))] (.remove (.-classList x) "selected")) (.add (.-classList b) "selected") (swap! state assoc :mode (keyword (.getAttribute b "data-mode"))))))
 (.addEventListener canvas "pointerdown" #(do (reset! dragging true) (swap! state (fn [s] (-> s (update :history conj (:mesh s)) (assoc :future []) (update :strokes inc)))) (brush-at! canvas %)))
 (.addEventListener js/window "pointerup" #(reset! dragging false)) (.addEventListener canvas "pointermove" #(when @dragging (brush-at! canvas %)))
 (.addEventListener (.getElementById js/document "radius") "input" #(let [v (js/parseFloat (.. % -target -value))] (swap! state assoc :radius v) (set! (.-textContent (.getElementById js/document "radius-value")) (.toFixed v 2))))
 (.addEventListener (.getElementById js/document "strength") "input" #(let [v (js/parseFloat (.. % -target -value))] (swap! state assoc :strength v) (set! (.-textContent (.getElementById js/document "strength-value")) (.toFixed v 2))))
 (.addEventListener (.getElementById js/document "symmetry") "change" #(swap! state assoc :symmetry (when (seq (.. % -target -value)) (keyword (.. % -target -value)))))
 (.addEventListener (.getElementById js/document "undo") "click" #(when-let [m (peek (:history @state))] (swap! state (fn [s] (assoc s :mesh m :history (pop (:history s)) :future (conj (:future s) (:mesh s))))) (upload!)))
 (.addEventListener (.getElementById js/document "redo") "click" (fn [] (when-let [m (peek (:future @state))] (swap! state (fn [s] (assoc s :mesh m :future (pop (:future s)) :history (conj (:history s) (:mesh s))))) (upload!))))
 (.addEventListener (.getElementById js/document "export") "click" #(let [a (.createElement js/document "a")] (set! (.-href a) (.createObjectURL js/URL (js/Blob. #js [(pr-str (:mesh @state))] #js {:type "application/edn"}))) (set! (.-download a) "sculpt.edn") (.click a)))))
